# Generated by Django 5.2.9 on 2025-12-16 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('pets', '0001_initial'),
        ('profissionais', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Início')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Hora Fim')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('nao_compareceu', 'Não Compareceu')], default='agendado', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('whatsapp_confirmacao_enviada', models.BooleanField(default=False, verbose_name='Confirmação WhatsApp enviada')),
                ('whatsapp_lembrete_enviado', models.BooleanField(default=False, verbose_name='Lembrete WhatsApp enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='clientes.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='pets.pet', verbose_name='Pet')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='profissionais.profissional', verbose_name='Profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(verbose_name='Data do Atendimento')),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Cobrado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='agendamentos.agendamento', verbose_name='Agendamento')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_atendimentos', to='pets.pet', verbose_name='Pet')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_atendimentos', to='profissionais.profissional', verbose_name='Profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_atendimentos', to='services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Histórico de Atendimento',
                'verbose_name_plural': 'Históricos de Atendimentos',
                'ordering': ['-data_atendimento'],
            },
        ),
    ]
