# Generated by Django 5.2.9 on 2025-12-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('preco_porte_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Porte Médio')),
                ('preco_porte_grande', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Porte Grande')),
                ('duracao_minutos', models.PositiveIntegerField(default=30, verbose_name='Duração (minutos)')),
                ('porte_aplicavel', models.CharField(choices=[('todos', 'Todos os portes'), ('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], default='todos', max_length=20, verbose_name='Porte Aplicável')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='services.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['-created_at'],
            },
        ),
    ]
