# Generated by Django 5.2.9 on 2025-12-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacao', 'Confirmação de Agendamento'), ('lembrete', 'Lembrete'), ('cancelamento', 'Cancelamento'), ('reagendamento', 'Reagendamento'), ('pos_atendimento', 'Pós-atendimento')], max_length=20, unique=True, verbose_name='Tipo')),
                ('template', models.TextField(verbose_name='Template da Mensagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Template de Mensagem',
                'verbose_name_plural': 'Templates de Mensagens',
            },
        ),
        migrations.CreateModel(
            name='MensagemEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('entregue', 'Entregue'), ('lida', 'Lida'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status')),
                ('erro_mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('enviada_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_whatsapp', to='agendamentos.agendamento', verbose_name='Agendamento')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.mensagemtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Mensagem Enviada',
                'verbose_name_plural': 'Mensagens Enviadas',
                'ordering': ['-created_at'],
            },
        ),
    ]
